version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: racon123!
      MYSQL_DATABASE: cykor_web1_db
    ports:
      - "3307:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d

volumes:
  db_data:
